name: Vérification Accessibilité RGAA

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  accessibility-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install accessibility tools
      run: |
        npm install --save-dev @axe-core/react @axe-core/cli eslint-plugin-jsx-a11y @testing-library/jest-axe pa11y lighthouse-ci
        
    - name: Run accessibility checks
      run: npm run accessibility:check
      
    - name: Run ESLint accessibility rules
      run: npm run lint:accessibility
      
    - name: Run accessibility tests
      run: npm run test:accessibility
      
    - name: Build application
      run: npm run build
      
    - name: Start application
      run: npm start &
      env:
        PORT: 3000
        
    - name: Wait for application
      run: npx wait-on http://localhost:3000
      
    - name: Run Lighthouse CI
      run: npm run accessibility:audit
      
    - name: Upload accessibility report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: accessibility-report
        path: |
          lhci_reports/
          accessibility-results.json
